export const LOAD_MOCK_VALUE = "LOAD_MOCK_VALUE";
export const MOCK_VALUE_LOADED = "MOCK_VALUE_LOADED";

export const USER_DATA = "USER_DATA";
export const NEW_USER_NAME = "NEW_USER_NAME";

export const BOARD_MINIATURES = "BOARD_MINIATURES";
