export const LOAD_MOCK_VALUE = "LOAD_MOCK_VALUE";
export const MOCK_VALUE_LOADED = "MOCK_VALUE_LOADED";

export const USER_SIGNED_IN = "USER_SIGNED_IN";
export const USER_SIGNED_OUT = "USER_SIGNED_OUT";
