export const UPDATE_USER = "USER_DATA";
export const UPDATE_USER_NAME = "NEW_USER_NAME";
export const UPDATE_USER_NAME_ERROR = "UPDATE_USER_NAME_ERROR";

export const GOT_BOARD_MINIATURES = "GOT_BOARD_MINIATURES";
export const GOT_BOARD_MINIATURES_ERROR = "GOT_BOARD_MINIATURES_ERROR";

export const GET_BOARD = "GET_BOARD";
export const GOT_BOARD = "GOT_BOARD";
export const GOT_BOARD_ERROR = "GOT_BOARD_ERROR";

export const RESET_BOARD = "RESET_BOARD";

export const RENAME_BOARD = "RENAME_BOARD";
export const RENAMED_BOARD = "RENAMED_BOARD";
export const RENAMED_BOARD_ERROR = "RENAMED_BOARD_ERROR";

export const CREATE_BOARD = "CREATE_BOARD";
export const CREATED_BOARD = "CREATED_BOARD";
export const CREATED_BOARD_ERROR = "CREATED_BOARD_ERROR";

export const DELETE_BOARD = "DELETE_BOARD";
export const DELETED_BOARD = "DELETED_BOARD";
export const DELETED_BOARD_ERROR = "DELETED_BOARD_ERROR";

export const CREATE_LIST = "CREATE_LIST";
export const CREATED_LIST = "CREATED_LIST";
export const CREATED_LIST_ERROR = "CREATED_LIST_ERROR";

export const RENAME_LIST = "RENAME_LIST";
export const RENAMED_LIST = "RENAMED_LIST";
export const RENAMED_LIST_ERROR = "RENAMED_LIST_ERROR";

export const DELETE_LIST = "DELETE_LIST";
export const DELETED_LIST = "DELETED_LIST";
export const DELETED_LIST_ERROR = "DELETED_LIST_ERROR";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const START_CREATING_TASK = "START_CREATING_TASK";
export const STOP_CREATING_TASK = "STOP_CREATING_TASK";

export const CREATE_TASK = "CREATE_TASK";
export const CREATED_TASK = "CREATED_TASK";
export const CREATED_TASK_ERROR = "CREATED_TASK_ERROR";

export const DELETE_TASK = "DELETE_TASK";
export const DELETED_TASK = "DELETED_TASK";
export const DELETED_TASK_ERROR = "DELETED_TASK_ERROR";

export const RENAME_TASK = "RENAME_TASK";
export const RENAMED_TASK = "RENAMED_TASK";
export const RENAMED_TASK_ERROR = "RENAMED_TASK_ERROR";

export const CHANGE_TASK_DESCRIPTION = "CHANGE_TASK_DESCRIPTION";
export const CHANGED_TASK_DESCRIPTION = "CHANGED_TASK_DESCRIPTION";
export const CHANGED_TASK_DESCRIPTION_ERROR = "CHANGED_TASK_DESCRIPTION_ERROR";

export const MOVE_LIST = "MOVE_LIST";
export const MOVE_LIST_SUCCESS = "MOVE_LIST_SUCCESS";
export const MOVE_LIST_ERROR = "MOVE_LIST_ERROR";

export const MOVE_TASK = "MOVE_TASK";
export const MOVE_TASK_SUCCESS = "MOVE_TASK_SUCCESS";
export const MOVE_TASK_ERROR = "MOVE_TASK_ERROR";

export const ADD_VIEWER = "ADD_VIEWER";
export const ADD_VIEWER_SUCCESS = "ADD_VIEWER_SUCCESS";
export const ADD_VIEWER_ERROR = "ADD_VIEWER_ERROR";

export const REMOVE_VIEWER = "REMOVE_VIEWER";
export const REMOVE_VIEWER_SUCCESS = "REMOVE_VIEWER_SUCCESS";
export const REMOVE_VIEWER_ERROR = "REMOVE_VIEWER_ERROR";

export const UNSUB_BOARD = "UNSUB_BOARD";
export const UNSUB_BOARD_SUCCESS = "UNSUB_BOARD_SUCCESS";
export const UNSUB_BOARD_ERROR = "UNSUB_BOARD_ERROR";

export const ADD_ATTACHMENT = "ADD_ATTACHMENT";
export const ADD_ATTACHMENT_SUCCESS = "ADD_ATTACHMENT_SUCCESS";
export const ADD_ATTACHMENT_ERROR = "ADD_ATTACHMENT_ERROR";

export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const REMOVE_ATTACHMENT_SUCCESS = "REMOVE_ATTACHMENT_SUCCESS";
export const REMOVE_ATTACHMENT_ERROR = "REMOVE_ATTACHMENT_ERROR";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";

export const EDIT_COMMENT = "EDIT_COMMENT";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR";

export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";
